package com.tap.daoimpl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.tap.connection.DBConnection;
import com.tap.dao.OrderDAO;
import com.tap.model.Order;

public class OrderDAOImpl implements OrderDAO {

    private static final String INSERT_ORDER = "INSERT INTO `orders` (`user_id`, `restaurant_id`, `address`, `payment_method`, `total_amount`, `status`) VALUES (?, ?, ?, ?, ?, ?)";
    private static final String SELECT_ORDER_BY_ID = "SELECT * FROM `orders` WHERE `order_id` = ?";
    private static final String UPDATE_ORDER = "UPDATE `orders` SET `user_id` = ?, `restaurant_id` = ?, `address` = ?, `payment_method` = ?, `total_amount` = ?, `status` = ? WHERE `order_id` = ?";
    private static final String DELETE_ORDER = "DELETE FROM `orders` WHERE `order_id` = ?";
    private static final String SELECT_ALL_ORDERS_BY_USER = "SELECT * FROM `orders` WHERE `user_id` = ? ORDER BY `order_date` DESC";

    @Override
    public int addOrder(Order order) {
        int orderId = 0;

        // Pass Statement.RETURN_GENERATED_KEYS to grab the primary key created by MySQL
        try (Connection con = DBConnection.getConnection();
             PreparedStatement statement = con.prepareStatement(INSERT_ORDER, Statement.RETURN_GENERATED_KEYS)) {

            statement.setInt(1, order.getUserId());
            statement.setInt(2, order.getRestaurantId());
            statement.setString(3, order.getAddress());
            statement.setString(4, order.getPaymentMethod());
            statement.setDouble(5, order.getTotalAmount());
            statement.setString(6, order.getStatus());

            int affectedRows = statement.executeUpdate();

            if (affectedRows > 0) {
                // Fetch the auto-incremented ID generated by the database
                try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        orderId = generatedKeys.getInt(1);
                    }
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return orderId; // Returns the generated order ID back to OrderServlet
    }

    @Override
    public Order getOrder(int orderId) {
        Order order = null;

        try (Connection con = DBConnection.getConnection();
             PreparedStatement statement = con.prepareStatement(SELECT_ORDER_BY_ID)) {

            statement.setInt(1, orderId);

            try (ResultSet res = statement.executeQuery()) {
                if (res.next()) {
                    order = extractOrderFromResultSet(res);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return order;
    }

    @Override
    public void updateOrder(Order order) {
        try (Connection con = DBConnection.getConnection();
             PreparedStatement statement = con.prepareStatement(UPDATE_ORDER)) {

            statement.setInt(1, order.getUserId());
            statement.setInt(2, order.getRestaurantId());
            statement.setString(3, order.getAddress());
            statement.setString(4, order.getPaymentMethod());
            statement.setDouble(5, order.getTotalAmount());
            statement.setString(6, order.getStatus());
            statement.setInt(7, order.getOrderId());

            statement.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void deleteOrder(int orderId) {
        try (Connection con = DBConnection.getConnection();
             PreparedStatement statement = con.prepareStatement(DELETE_ORDER)) {

            statement.setInt(1, orderId);
            statement.executeUpdate();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    public List<Order> getAllOrdersByUser(int userId) {
        List<Order> orderList = new ArrayList<>();

        try (Connection con = DBConnection.getConnection();
             PreparedStatement statement = con.prepareStatement(SELECT_ALL_ORDERS_BY_USER)) {

            statement.setInt(1, userId);

            try (ResultSet res = statement.executeQuery()) {
                while (res.next()) {
                    Order order = extractOrderFromResultSet(res);
                    orderList.add(order);
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return orderList;
    }

    // Common utility method to map database result rows into Java objects
    private Order extractOrderFromResultSet(ResultSet res) throws SQLException {
        Order order = new Order();
        order.setOrderId(res.getInt("order_id"));
        order.setOrderDate(res.getTimestamp("order_date"));
        order.setUserId(res.getInt("user_id"));
        order.setRestaurantId(res.getInt("restaurant_id"));
        order.setAddress(res.getString("address"));
        order.setPaymentMethod(res.getString("payment_method"));
        order.setTotalAmount(res.getDouble("total_amount"));
        order.setStatus(res.getString("status"));
        return order;
    }
}